events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Машрутизация микросервиса пользователей
        location /api/User/ {
            proxy_pass http://users.web:8080/api/User/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/Profile/ {
            proxy_pass http://users.web:8080/api/Profile/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Всё остальное (статика и основное API AskDate) идёт в askdate.web
        location / {
            proxy_pass http://askdate.web:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}